project:
  type: website

website:
  title: "simple_quarto_website"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: slides/slides.ipynb
        text: Slides
      - about.ipynb

format:
  html:
    theme: cosmo
    toc: true
    toc-location: left
    bibliography: reference.bib



